backend-frontend/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users
  resources :sessions,            only: :create
  resources :confirmations,       only: :show
  resources :passwords,           except: [:index, :show, :destroy]
  resources :problems,            except: :index
  resources :requests,            except: :index
  resources :incidents,           except: :index
  resources :solutions_problems,  except: :index
  resources :solutions_incidents, except: :index
  resources :solutions_requests,  except: :index
  resources :comments_requests,   except: [:index, :show]
  resources :comments_problems,   except: [:index, :show]
  resources :comments_incidents,  except: [:index, :show]

  get 'home' => 'homes#index',           as: :home
  get 'login' => 'sessions#new',         as: :login
  delete 'logout' => 'sessions#destroy', as: :logout 
  post 'problems/finished/:id' => 'problems#finished'
  post 'problems/open/:id' => 'problems#open'
  post 'requests/finished/:id' => 'requests#finished'
  post 'requests/open/:id' => 'requests#open'
  post 'incidents/finished/:id' => 'incidents#finished'
  post 'incidents/open/:id' => 'incidents#open'
end

backend-frontend/app/models/request.rb
class Request < ActiveRecord::Base
  
  # Associations
  belongs_to :user
  has_many :comments_requests,  dependent: :delete_all

  # Validations
  validates :title, :description, :user_id, presence: true

  # Methods
  def is_finished?
    self.state == 'answered' ? true : false
  end

  def has_one_comment?
    self.comments_requests.count == 1 ? true : false
  end
end

backend-frontend/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  before_action :find_request, only: [:update, :destroy, :finished, :open]

  def show
    @request = current_user.is_customer? ? current_user.requests.find(params[:id]) : Request.find(params[:id])
    if @request
      @comments_requests = @request.comments_requests
      @comments_request = CommentsRequest.new
    end
  end

  def new
    respond_to do |format|
      @request = Request.new
      format.js
    end
  end

  def create
    respond_to do |format|
      @request = current_user.requests.build(params_request)
      @request.save
      flash[:notice] = 'Sugerencia creada exitosamente'
      format.js  
    end
  end

  def edit
    respond_to do |format|
      @request = Request.find(params[:id])
      format.js
    end
  end

  def update
    respond_to do |format|
      if current_user.creator_cases?(params[:id], 'request') || current_user.is_sa?
        @request.assign_attributes(params_request)
        @request.save
        flash[:notice] = 'Se ha actualizado correctamente la sugerencia'
        format.js
      else
        redirect_to :home
      end
      
    end
  end

  def destroy
    if current_user.creator_cases?(params[:id], 'request') || current_user.is_sa?
      @request.destroy
      flash[:notice] = 'Sugerencia eliminada correctamente'
    end
    redirect_to :home
  end

  def finished
    change_state(@request, 'answered')
    redirect_to request_path(params[:id])
  end

  def open
    change_state(@request, 'active')
    redirect_to request_path(params[:id])
  end

  private
  def params_request
    params.require(:request).permit(:title, :description)
  end

  def find_request
    @request = Request.find(params[:id])
  end

  def change_state(request, state)
    request.assign_attributes(state: state)
    request.save
  end
end

backend-frontend/app/helpers/requests_helper.rb
module RequestsHelper
end

backend-frontend/app/views/requests/create.js.erb
if (<%= !@request.errors.empty? %>) {
  $('#error-title-request').html(function() { return  "<%= @request.errors[:title].join(', ') %>" })
  $('#error-description-request').html(function() { return  "<%= @request.errors[:description].join(', ') %>" })
}else{
  location.reload()
}

backend-frontend/app/views/requests/edit.js.erb
$('#modal-9 #request_title').val("<%= @request.title %>")
$('#modal-9 #request_description').val("<%= @request.description %>")
$('#new_request').attr('action', "<%= request_path(@request) %>");
$('#new_request').attr('method', 'patch');

backend-frontend/app/views/requests/new.js.erb
$('#new_request').attr('action', "<%= requests_path %>");
$('#new_request').attr('method', 'post');

backend-frontend/app/views/requests/show.html.erb
    <!-- Modal -->
    <div class="md-modal md-effect-8" id="modal-8">
      <div class="md-content">
        <div class="form-panel">
          <h3 class="mb">Responder</h3>
          <%= form_for(@comments_request, remote: true) do |f| %>
            <form class="form-horizontal tasi-form" method="get">
              <div class="form-group has-success">
                <label class="col-sm-2 control-label col-lg-2" for="inputWarning">Descripción</label>
                <%= f.text_area(:description, rows: 12, class: 'form-control' ) %>
                <span id="error-description"></span>
              </div>
              <%= f.hidden_field :request_id, value: @request.id %>
              <div >
                <button type="submit"  name="commit"> Enviar</button>
                <button type="button" class="md-close" onclick="clear_span()">Cancelar</button> 
              </div>     
            </form>
          <% end %>       
        </div>
      </div>
    </div>
    <div class="md-modal md-effect-8" id="modal-9">
      <div class="md-content">
        <div class="form-panel">
          <h3 class="mb">Problemas</h3>
          <%= form_for(@request, remote: true) do |f| %>
            <form class="form-horizontal tasi-form" method="get">
              <div class="form-group has-success">
                <label class="col-sm-2 control-label col-lg-2">Titulo</label>
                <%= f.text_field(:title, class: 'form-control') %>
                <span id="error-title-request"></span>
              </div>
              <div class="form-group has-success">
                <label class="col-sm-2 control-label col-lg-2" for="inputWarning">Descripción</label>
                <%= f.text_area(:description, rows: 12, class: 'form-control' ) %>
                <span id="error-description-request"></span>
              </div>
              <div>
              <button type="submit" name="commit">Enviar</input>
              <button type="button" class="md-close" onclick="clear_span()">Cancelar</button>  
            </form>                      
            </div>
          <% end %> 
        </div>
      </div>
    </div>
    <!-- End modal -->
    <section id="container" class="sidebar-closed container" >
        <!-- Header -->
          <%= render 'shared/header'%>
        <!-- End header -->
        <div id="main-content" class="wrapper">
          <div class="comments-container">
            <ul id="comments-list" class="comments-list">
              <li>
                <div class="comment-main-level">
                  <div class="comment-avatar"><i class="fa fa-question fa-4x"></i></div>
                  <div class="comment-box">
                    <div class="comment-head">
                      <h6 class="comment-name by-author"><a href="#"><%= @request.title %></a></h6>
                      <span> <%= @request.created_at.to_formatted_s(:long) %> </span>
                      <% unless @request.is_finished? %>
                        <% if @comments_requests.empty? %>
                          <a href='/comments_requests/new' data-remote="true" class="md-trigger" data-modal="modal-8"> <i class="fa fa-reply fa-1x"></i></a>
                        <% end %>
                        <%  if current_user.creator_cases?(@request.id, 'request') || current_user.is_sa? %> 
                            <a href="/requests/<%= @request.id %>/edit" class="md-trigger" data-modal="modal-9" data-remote="true"><i class="fa fa-pencil"></i></a>
                           <a href=<%= request_path(@request) %> data-method="delete"><i class="fa fa-trash-o "></i></a>
                        <% end %>
                      <% end %>
                    </div>
                    <div class="comment-content">
                      <%= simple_format(@request.description) %>
                    </div>
                  </div>
                </div>
                <% @comments_requests.each_with_index do |comments_request, i| %>
                  <% if comments_request.user.is_customer? %>
                    <div class="comment-main-level">
                      <div class="comment-avatar"><i class="fa fa-question fa-4x"></i></div>
                      <div class="comment-box">
                        <div class="comment-head">
                          <h6 class="comment-name by-author"><a href="#"><%= comments_request.user.full_name %></a></h6>
                          <span> <%= comments_request.updated_at.to_formatted_s(:long) %> </span>
                          <% unless @request.is_finished? %>
                            <% if @comments_requests.size == i + 1 %>
                              <a href='/comments_requests/new' data-remote="true" class="md-trigger" data-modal="modal-8"> <i class="fa fa-reply fa-1x"></i></a>
                            <% end %>
                            <% if current_user.creator_comments?(comments_request.id, 'request') || current_user.is_sa? %>
                              <a href="/comments_requests/<%= comments_request.id %>/edit" class="md-trigger" data-modal="modal-8" data-remote="true"><i class="fa fa-pencil"></i></a>
                              <a href=<%= comments_request_path(comments_request, request_id: @request.id) %> data-method="delete" ><i class="fa fa-trash-o" ></i></a>
                            <% end %>
                          <% end %>
                        </div>
                        <div class="comment-content">
                          <%= simple_format(comments_request.description) %>
                        </div>
                      </div>
                    </div>
                  <% else %>
                    <ul class="comments-list reply-list">
                      <li>
                        <div class="comment-main-level">
                        <div class="comment-avatar"><i class="fa fa-check fa-3x"></i></div>
                          <div class="comment-box">
                            <div class="comment-head">
                              <h6 class="comment-name"><a href="#"><%= comments_request.user.full_name %></a></h6>
                              <span><%= comments_request.updated_at.to_formatted_s(:long) %></span>
                              <% unless @request.is_finished? %>
                                <% if @comments_requests.size == i + 1 %>
                                  <a href='/comments_requests/new' data-remote="true" class="md-trigger" data-modal="modal-8"> <i class="fa fa-reply fa-1x"></i></a>
                                <% end %>
                                <% if current_user.creator_comments?(comments_request.id, 'request') || current_user.is_sa? %>
                                  <a href="/comments_requests/<%= comments_request.id %>/edit" class="md-trigger" data-modal="modal-8" data-remote="true"><i class="fa fa-pencil"></i></a>
                                  <a href=<%= comments_request_path(comments_request, request_id: @request.id) %> data-method="delete" ><i class="fa fa-trash-o" ></i></a>
                                <% end %>
                              <% end %>
                            </div>
                            <div class="comment-content">
                              <%= simple_format(comments_request.description) %>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  <% end %>
                <% end %>
                <% if current_user.creator_cases?(@request.id, 'request') || current_user.is_sa? %>
                  <div class="close-case">
                    <% if @request.state != 'answered' %>
                      <a class ="not-solve" href="/requests/finished/<%= @request.id %>" data-method="post">
                        <i class="fa fa-ban fa-2x"></i>
                      </a>
                    <% else %>
                      <a class ="solve" href="/requests/open/<%= @request.id %>" data-method="post">
                        <i class="fa fa-ban fa-2x"></i>
                      </a>
                      <span> Caso cerrado el <b> <%= @request.updated_at.to_formatted_s(:long) %> </b> </span>
                    <% end %>
                  </div>
                <% else %>
                  <% if @request.is_finished? %>
                    <div class="close-case">
                      <a class ="solve" href='#'>
                        <i class="fa fa-ban fa-2x"></i>
                      </a>
                      <span> Caso cerrado el <b> <%= @request.updated_at.to_formatted_s(:long) %> </b> </span>
                    </div>
                  <% end %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
    </section>
    
    

backend-frontend/app/views/requests/update.js.erb
if (<%= !@request.errors.empty? %>) {
  $('#error-title-request').html(function() { return  "<%= @request.errors[:title].join(', ') %>" })
  $('#error-description-request').html(function() { return  "<%= @request.errors[:description].join(', ') %>" })
}else{
  location.reload()
}