backend-frontend/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users
  resources :sessions,            only: :create
  resources :confirmations,       only: :show
  resources :passwords,           except: [:index, :show, :destroy]
  resources :problems,            except: :index
  resources :requests,            except: :index
  resources :incidents,           except: :index
  resources :solutions_problems,  except: :index
  resources :solutions_incidents, except: :index
  resources :solutions_requests,  except: :index
  resources :comments_requests,   except: [:index, :show]
  resources :comments_problems,   except: [:index, :show]
  resources :comments_incidents,  except: [:index, :show]

  get 'home' => 'homes#index',           as: :home
  get 'login' => 'sessions#new',         as: :login
  delete 'logout' => 'sessions#destroy', as: :logout 
  post 'problems/finished/:id' => 'problems#finished'
  post 'problems/open/:id' => 'problems#open'
  post 'requests/finished/:id' => 'requests#finished'
  post 'requests/open/:id' => 'requests#open'
  post 'incidents/finished/:id' => 'incidents#finished'
  post 'incidents/open/:id' => 'incidents#open'
end

backend-frontend/app/models/problem.rb
class Problem < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :comments_problems,  dependent: :delete_all

  # Validations
  validates :title, :description, :user_id, presence: true

  # Methods
  def is_finished?
    self.state == 'answered' ? true : false
  end

  def has_one_comment?
    self.comments_problems.count == 1 ? true : false
  end
end

backend-frontend/app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  
  before_action :find_problem, only: [:update, :destroy, :finished, :open]

  def show
    @problem = current_user.is_customer? ? current_user.problems.find(params[:id]) : Problem.find(params[:id])
    if @problem
      @comments_problems = @problem.comments_problems
      @comments_problem = CommentsProblem.new
    end
  end

  def new
    respond_to do |format|
      @problem = Problem.new
      format.js
    end
  end

  def create 
    respond_to do |format|
      @problem = current_user.problems.build(problem_params)
      @problem.save
      flash[:notice] = 'Problema creado exitosamente'
      format.js
    end
  end

  def edit
    respond_to do |format|
      @problem = Problem.find(params[:id])
      format.js
    end
  end

  def update
    respond_to do |format|
      if current_user.creator_cases?(params[:id], 'problem') || current_user.is_sa?
    	  @problem.assign_attributes(problem_params)
    	  @problem.save
        flash[:notice] = 'Se ha actualizado correctamente el problema'
        format.js
      else
        redirect_to :home
      end
    end
  end

  def destroy
    if current_user.creator_cases?(params[:id], 'problem') || current_user.is_sa?
    	@problem.destroy
      flash[:notice] = 'Problema eliminado correctamente'
    end
    redirect_to :home
  end

  def finished
    change_state(@problem, 'answered')
    redirect_to problem_path(params[:id])
  end

  def open
    change_state(@problem, 'active')
    redirect_to problem_path(params[:id])
  end

  private
  def problem_params
  	params.require(:problem).permit(:title, :description)
  end

  def find_problem
  	@problem = Problem.find(params[:id])
  end

  def change_state(problem, state)
    problem.assign_attributes(state: state)
    problem.save
  end
end

backend-frontend/app/helpers/problems_helper.rb
module ProblemsHelper
end

backend-frontend/app/views/problems/create.js.erb
if (<%= !@problem.errors.empty? %>) {
  $('#error-title-problem').html(function() { return  "<%= @problem.errors[:title].join(', ') %>" })
  $('#error-description-problem').html(function() { return  "<%= @problem.errors[:description].join(', ') %>" })
} else {
  location.reload()
}

backend-frontend/app/views/problems/edit.js.erb
$('#modal-10 #problem_title').val("<%= @problem.title %>")
$('#modal-10 #problem_description').val("<%= @problem.description %>")
$('#new_problem').attr('action', "<%= problem_path(@problem) %>");
$('#new_problem').attr('method', 'patch');

backend-frontend/app/views/problems/new.js.erb
$('#new_problem').attr('action', "<%= problems_path %>");
$('#new_problem').attr('method', 'post');

backend-frontend/app/views/problems/show.html.erb
<!-- Modal -->
<div class="md-modal md-effect-8" id="modal-8">
  <div class="md-content">
    <div class="form-panel">
      <h3 class="mb">Responder</h3>
      <%= form_for(@comments_problem, remote: true) do |f| %>
        <form class="form-horizontal tasi-form" method="get">
          <div class="form-group has-success">
            <label class="col-sm-2 control-label col-lg-2" for="inputWarning">Descripción</label>
            <%= f.text_area(:description, rows: 12, class: 'form-control' ) %>
            <span id="error-description"></span>
          </div>
          <%= f.hidden_field :problem_id, value: @problem.id %>
          <div >
            <button type="submit"  name="commit"> Enviar</button>
            <button type="button" class="md-close" onclick="clear_span()">Cancelar</button> 
          </div>     
        </form>
      <% end %>       
    </div>
  </div>
</div>
<div class="md-modal md-effect-8" id="modal-9">
  <div class="md-content">
    <div class="form-panel">
      <h3 class="mb">Problemas</h3>
      <%= form_for(@problem, remote: true) do |f| %>
        <form class="form-horizontal tasi-form" method="get">
          <div class="form-group has-success">
            <label class="col-sm-2 control-label col-lg-2">Titulo</label>
            <%= f.text_field(:title, class: 'form-control') %>
            <span id="error-title-problem"></span>
          </div>
          <div class="form-group has-success">
            <label class="col-sm-2 control-label col-lg-2" for="inputWarning">Descripción</label>
            <%= f.text_area(:description, rows: 12, class: 'form-control' ) %>
            <span id="error-description-problem"></span>
          </div>
          <div>
          <button type="submit" name="commit">Enviar</input>
          <button type="button" class="md-close" onclick="clear_span()"> Cancelar</button>  
        </form>                      
        </div>
      <% end %> 
    </div>
  </div>
</div>
<!-- End modal -->
<section id="container" class="sidebar-closed container" >
    <!-- Header -->
      <%= render 'shared/header'%>
    <!-- End header -->
    <div id="main-content" class="wrapper">
      <div class="comments-container">
        <ul id="comments-list" class="comments-list">
          <li>
            <div class="comment-main-level">
              <div class="comment-avatar"><i class="fa fa-question fa-4x"></i></div>
              <div class="comment-box">
                <div class="comment-head">
                  <h6 class="comment-name by-author"><a href="#"><%= @problem.title %></a></h6>
                  <span> <%= @problem.created_at.to_formatted_s(:long) %> </span>
                  <% unless @problem.is_finished? %>
                    <% if current_user.creator_cases?(@problem.id, 'problem') || current_user.is_sa? %> 
                      <a href=<%= problem_path(@problem) %> data-method="delete"><i class="fa fa-trash-o "></i></a>
                       <a href="/problems/<%= @problem.id %>/edit" class="md-trigger" data-modal="modal-9" data-remote="true"><i class="fa fa-pencil"></i></a>
                    <% end %>
                    <% if @comments_problems.empty? %>
                      <a href='/comments_problems/new' data-remote="true" class="md-trigger" data-modal="modal-8"> <i class="fa fa-reply fa-1x"></i></a>
                    <% end %>
                  <% end %>
                </div>
                <div class="comment-content">
                  <%= simple_format(@problem.description) %>
                </div>
              </div>
            </div>
            <% @comments_problems.each_with_index do |comments_problem, i| %>
              <% if comments_problem.user.is_customer? %>
                <div class="comment-main-level">
                  <div class="comment-avatar"><i class="fa fa-question fa-4x"></i></div>
                  <div class="comment-box">
                    <div class="comment-head">
                      <h6 class="comment-name by-author"><a href="#"><%= comments_problem.user.full_name %></a></h6>
                      <span> <%= comments_problem.updated_at.to_formatted_s(:long) %> </span>
                      <% unless @problem.is_finished? %>
                        <% if @comments_problems.size == i + 1 %>
                          <a href='/comments_problems/new' data-remote="true" class="md-trigger" data-modal="modal-8"> <i class="fa fa-reply fa-1x"></i></a>
                        <% end %>
                        <% if current_user.creator_comments?(comments_problem.id, 'problem') || current_user.is_sa? %>
                          <a href="/comments_problems/<%= comments_problem.id %>/edit" class="md-trigger" data-modal="modal-8" data-remote="true"><i class="fa fa-pencil"></i></a>
                          <a href=<%= comments_problem_path(comments_problem, problem_id: @problem.id) %> data-method="delete" ><i class="fa fa-trash-o" ></i></a>
                        <% end %>
                      <% end %>
                    </div>
                    <div class="comment-content">
                      <%= simple_format(comments_problem.description) %>
                    </div>
                  </div>
                </div>
              <% else %>
                <ul class="comments-list reply-list">
                  <li>
                    <div class="comment-main-level">
                    <div class="comment-avatar"><i class="fa fa-check fa-3x"></i></div>
                      <div class="comment-box">
                        <div class="comment-head">
                          <h6 class="comment-name"><a href="#"><%= comments_problem.user.full_name %></a></h6>
                          <span><%= comments_problem.updated_at.to_formatted_s(:long) %></span>
                          <% unless @problem.is_finished? %>
                            <% if @comments_problems.size == i + 1 %>
                              <a href='/comments_problems/new' data-remote="true" class="md-trigger" data-modal="modal-8"> <i class="fa fa-reply fa-1x"></i></a>
                            <% end %>
                            <% if current_user.creator_comments?(comments_problem.id, 'problem') || current_user.is_sa? %>
                              <a href="/comments_problems/<%= comments_problem.id %>/edit" class="md-trigger" data-modal="modal-8" data-remote="true"><i class="fa fa-pencil"></i></a>
                              <a href=<%= comments_problem_path(comments_problem, problem_id: @problem.id) %> data-method="delete" ><i class="fa fa-trash-o" ></i></a>
                            <% end %>
                          <% end %>
                        </div>
                        <div class="comment-content">
                          <%= simple_format(comments_problem.description) %>
                        </div>
                      </div>
                    </div>
                  </li>
                </ul>
              <% end %>
            <% end %>
            <% if current_user.creator_cases?(@problem.id, 'problem') || current_user.is_sa? %>
              <div class="close-case">
                <% if @problem.state != 'answered' %>
                  <a class ="not-solve" href="/problems/finished/<%= @problem.id %>" data-method="post">
                    <i class="fa fa-ban fa-2x"></i>
                  </a>
                <% else %>
                  <a class ="solve" href="/problems/open/<%= @problem.id %>" data-method="post">
                    <i class="fa fa-ban fa-2x"></i>
                  </a>
                  <span> Caso cerrado el <b> <%= @problem.updated_at.to_formatted_s(:long) %> </b> </span>
                <% end %>
              </div>
            <% else %>
              <% if @problem.is_finished? %>
                <div class="close-case">
                  <a class ="solve" href='#' >
                    <i class="fa fa-ban fa-2x"></i>
                  </a>
                  <span> Caso cerrado el <b> <%= @problem.updated_at.to_formatted_s(:long) %> </b> </span>
                </div>
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
</section>

backend-frontend/app/views/problems/update.js.erb
if (<%= !@problem.errors.empty? %>) {
  $('#error-title-problem').html(function() { return  "<%= @problem.errors[:title].join(', ') %>" })
  $('#error-description-problem').html(function() { return  "<%= @problem.errors[:description].join(', ') %>" })
}else{
  location.reload() 
}