backend-frontend/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users
  resources :sessions,            only: :create
  resources :confirmations,       only: :show
  resources :passwords,           except: [:index, :show, :destroy]
  resources :problems,            except: :index
  resources :requests,            except: :index
  resources :incidents,           except: :index
  resources :solutions_problems,  except: :index
  resources :solutions_incidents, except: :index
  resources :solutions_requests,  except: :index
  resources :comments_requests,   except: [:index, :show]
  resources :comments_problems,   except: [:index, :show]
  resources :comments_incidents,  except: [:index, :show]

  get 'home' => 'homes#index',           as: :home
  get 'login' => 'sessions#new',         as: :login
  delete 'logout' => 'sessions#destroy', as: :logout 
  post 'problems/finished/:id' => 'problems#finished'
  post 'problems/open/:id' => 'problems#open'
  post 'requests/finished/:id' => 'requests#finished'
  post 'requests/open/:id' => 'requests#open'
  post 'incidents/finished/:id' => 'incidents#finished'
  post 'incidents/open/:id' => 'incidents#open'
end

backend-frontend/app/models/comments_problem.rb
class CommentsProblem < ActiveRecord::Base
  belongs_to :user
  belongs_to :problem

  validates :description, :user_id, :problem_id, presence: true
end

backend-frontend/app/controllers/comments_problems_controller.rb
class CommentsProblemsController < ApplicationController
  
  before_action :find_comments_problem, except: [:new, :create, :edit]

  def new
    respond_to do |format|
      @comments_problem = CommentsProblem.new
      format.js
    end
  end

  def create
    respond_to do |format|
      problem_id = params[:comments_problem][:problem_id]
      if current_user.creator_cases?(problem_id, 'problem') || current_user.is_sa? || current_user.is_admin?
         @comments_problem = current_user.comments_problems.build(params_comments_problem)
        if @comments_problem.save
          change_state(@comments_problem, 'active')
        end
      end
      format.js
    end
  end

  def edit
    respond_to do |format|
      @comments_problem = CommentsProblem.find(params[:id])
      format.js
    end
  end

  def update
    respond_to do |format|
      problem_id = params[:comments_problem][:problem_id]
      if current_user.creator_cases?(problem_id, 'problem') || current_user.is_sa? || current_user.is_admin?
        @comments_problem.assign_attributes(params_comments_problem)
        @comments_problem.save
      end
      format.js
    end
  end

  def destroy
    if current_user.creator_cases?(params[:id], 'problem') || current_user.is_sa? || current_user.is_admin?
      change_state(@comments_problem, 'unanswered') if @comments_problem.problem.has_one_comment?
      @comments_problem.destroy
      redirect_to problem_path(params[:problem_id])
    end
  end

  private
  def find_comments_problem 
    @comments_problem = CommentsProblem.find(params[:id])
  end

  def params_comments_problem
    params.require(:comments_problem).permit(:description, :problem_id)
  end

  def change_state(comments_problem, state)
    problem = comments_problem.problem
    problem.assign_attributes(state: state)
    problem.save
  end
end

backend-frontend/app/helpers/comments_problems_helper.rb
module CommentsProblemsHelper
end

backend-frontend/app/views/comments_problems/create.js.erb
if (<%= !@comments_problem.errors.empty? %>) {
  $('#error-description').html(function() { return  "<%= @comments_problem.errors[:description].join(', ') %>" })
}else{
  location.reload()
}

backend-frontend/app/views/comments_problems/edit.js.erb
$('#modal-8 #comments_problem_description').val("<%= @comments_problem.description %>")
$('#new_comments_problem').attr('action', "<%= comments_problem_path(@comments_problem) %>");
$('#new_comments_problem').attr('method', 'patch');

backend-frontend/app/views/comments_problems/new.js.erb
$('#new_comments_problem').attr('action', "<%= comments_problems_path %>");
$('#new_comments_problem').attr('method', 'post');

backend-frontend/app/views/comments_problems/update.js.erb
if (<%= !@comments_problem.errors.empty? %>) {
  $('#error-description').html(function() { return  "<%= @comments_problem.errors[:description].join(', ') %>" })
}else{
  location.reload()
}