backend-frontend/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users
  resources :sessions,            only: :create
  resources :confirmations,       only: :show
  resources :passwords,           except: [:index, :show, :destroy]
  resources :problems,            except: :index
  resources :requests,            except: :index
  resources :incidents,           except: :index
  resources :solutions_problems,  except: :index
  resources :solutions_incidents, except: :index
  resources :solutions_requests,  except: :index
  resources :comments_requests,   except: [:index, :show]
  resources :comments_problems,   except: [:index, :show]
  resources :comments_incidents,  except: [:index, :show]

  get 'home' => 'homes#index',           as: :home
  get 'login' => 'sessions#new',         as: :login
  delete 'logout' => 'sessions#destroy', as: :logout 
  post 'problems/finished/:id' => 'problems#finished'
  post 'problems/open/:id' => 'problems#open'
  post 'requests/finished/:id' => 'requests#finished'
  post 'requests/open/:id' => 'requests#open'
  post 'incidents/finished/:id' => 'incidents#finished'
  post 'incidents/open/:id' => 'incidents#open'
end

backend-frontend/app/views/shared/_header.html.erb
<header class="header black-bg">
  <a href='/' class="logo"><b><%= 'HELP DESK' %></b></a>
  <div class="nav notify-row" id="top_menu">
  <ul class="nav top-menu">
    <li>
      <a href="/">
        <i class="fa fa-home"> </i>
      </a>
    </li>
    <% if current_user.is_sa? %>
      <li>
        <a href= <%= users_path %> >
          <i class="fa fa-users"></i>
        </a>
      </li>
      <li>
        <a href= <%= new_user_path %> >
          <i class="fa fa-user-plus"></i>
        </a>
      </li>
    <% end %>
  </ul>
  </div>
  <div class="top-menu">
    <ul class="nav pull-right top-menu">
      <li>
        <a class="logout" href= <%= logout_path %>  data-method="delete">
          <i class="fa fa-sign-out fa-1x"> </i>
        </a>
      </li>
    </ul>
  </div>
</header>